name = "oink_lock"
version = "1.0.0"
license = "Apache-2.0"
description = "Lock contract for $oink tokens on Cardano"

[repository]
user = "oink"
project = "midoink-bridge"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

